//! Field extensions - adding capabilities to an agent's capability space.
//!
//! An extension K/F represents adding new capabilities to a base set.
//! The degree of the extension measures how much the capability space grows.

use serde::{Deserialize, Serialize};
use crate::field::{Capability, CapabilityField};

/// A capability extension: adding new capabilities to a base field.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CapabilityExtension {
    /// Name of this extension.
    pub name: String,
    /// The base field (what we start with).
    pub base: CapabilityField,
    /// The extended field (what we end up with).
    pub extended: CapabilityField,
    /// The "adjoined" capabilities (the new stuff).
    pub adjoined: Vec<String>,
}

impl CapabilityExtension {
    /// Create an extension by adjoining capabilities to a base field.
    pub fn new(name: &str, base: CapabilityField, new_caps: Vec<Capability>) -> Self {
        let mut extended = base.clone();
        let mut adjoined = Vec::new();
        for cap in &new_caps {
            extended.add_capability(cap.clone());
            adjoined.push(cap.name.clone());
        }
        Self {
            name: name.to_string(),
            base,
            extended,
            adjoined,
        }
    }

    /// The degree of the extension: [K:F] = |K| / |F|.
    pub fn degree(&self) -> usize {
        if self.base.degree() == 0 {
            return self.extended.degree();
        }
        self.extended.degree() / self.base.degree()
    }

    /// Check if this is a trivial extension (base == extended).
    pub fn is_trivial(&self) -> bool {
        self.base.equals(&self.extended)
    }

    /// Check if the extension is simple (generated by a single element).
    pub fn is_simple(&self) -> bool {
        self.adjoined.len() == 1
    }

    /// Check if this is a finite extension.
    pub fn is_finite(&self) -> bool {
        true // In our model, all extensions are finite
    }

    /// The minimal polynomial degree of the adjoined element (for simple extensions).
    /// In our metaphor, this is the minimum number of prerequisite capabilities needed.
    pub fn minimal_degree(&self) -> Option<u32> {
        if self.adjoined.len() != 1 {
            return None;
        }
        self.extended.get(&self.adjoined[0]).map(|c| c.power)
    }

    /// Compose two extensions: if L/K and K/F, then L/F.
    pub fn compose(&self, other: &CapabilityExtension) -> Result<CapabilityExtension, String> {
        // other's extended must match our base (approximately)
        let compositum = self.extended.compositum(&other.extended);
        Ok(CapabilityExtension {
            name: format!("{} ∘ {}", self.name, other.name),
            base: self.base.clone(),
            extended: compositum,
            adjoined: [
                self.adjoined.clone(),
                other.adjoined.clone(),
            ].concat(),
        })
    }

    /// Check if another extension is an intermediate extension.
    pub fn is_intermediate(&self, other: &CapabilityExtension) -> bool {
        self.extended.is_subfield_of(&other.extended) &&
            other.base.is_subfield_of(&self.base)
    }

    /// Find all intermediate fields between base and extended.
    pub fn intermediate_fields(&self) -> Vec<CapabilityField> {
        // Generate all subsets of adjoined capabilities
        let mut intermediates = Vec::new();
        let n = self.adjoined.len();
        for mask in 1u64..(1u64 << n) {
            let mut field = self.base.clone();
            field.name = format!("intermediate_{}", mask);
            for i in 0..n {
                if (mask >> i) & 1 == 1 {
                    if let Some(cap) = self.extended.get(&self.adjoined[i]) {
                        field.add_capability(cap.clone());
                    }
                }
            }
            intermediates.push(field);
        }
        intermediates
    }

    /// The tower of extensions (splitting into simple extensions).
    pub fn tower(&self) -> Vec<CapabilityExtension> {
        self.adjoined.iter().map(|cap_name| {
            let cap = self.extended.get(cap_name).cloned()
                .unwrap_or_else(|| Capability::new(cap_name, 1));
            CapabilityExtension::new(
                &format!("step_{}", cap_name),
                self.base.clone(),
                vec![cap],
            )
        }).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_simple_extension() {
        let base = CapabilityField::new("base");
        let ext = CapabilityExtension::new("add_perceive", base, vec![
            Capability::new("perceive", 1),
        ]);
        assert!(ext.is_simple());
        assert!(!ext.is_trivial());
        assert_eq!(ext.adjoined.len(), 1);
    }

    #[test]
    fn test_extension_degree() {
        let mut base = CapabilityField::new("base");
        base.add_capability(Capability::new("a", 1));
        let ext = CapabilityExtension::new("extend", base, vec![
            Capability::new("b", 1),
            Capability::new("c", 1),
        ]);
        assert_eq!(ext.degree(), 3); // 3 total / 1 base
    }

    #[test]
    fn test_trivial_extension() {
        let mut base = CapabilityField::new("base");
        base.add_capability(Capability::new("a", 1));
        let ext = CapabilityExtension::new("trivial", base.clone(), vec![]);
        assert!(ext.is_trivial());
    }

    #[test]
    fn test_minimal_degree() {
        let base = CapabilityField::new("base");
        let ext = CapabilityExtension::new("extend", base, vec![
            Capability::new("complex", 5),
        ]);
        assert_eq!(ext.minimal_degree(), Some(5));
    }

    #[test]
    fn test_non_simple_minimal_degree() {
        let base = CapabilityField::new("base");
        let ext = CapabilityExtension::new("extend", base, vec![
            Capability::new("a", 1),
            Capability::new("b", 1),
        ]);
        assert_eq!(ext.minimal_degree(), None); // not simple
    }

    #[test]
    fn test_compose_extensions() {
        let base = CapabilityField::new("base");
        let ext1 = CapabilityExtension::new("step1", base, vec![
            Capability::new("a", 1),
        ]);
        let ext2 = CapabilityExtension::new("step2", CapabilityField::new("mid"), vec![
            Capability::new("b", 1),
        ]);
        let composed = ext1.compose(&ext2).unwrap();
        assert!(composed.extended.contains("a"));
        assert!(composed.extended.contains("b"));
    }

    #[test]
    fn test_intermediate_fields() {
        let base = CapabilityField::new("base");
        let ext = CapabilityExtension::new("extend", base, vec![
            Capability::new("a", 1),
            Capability::new("b", 1),
            Capability::new("c", 1),
        ]);
        let intermediates = ext.intermediate_fields();
        // 2^3 - 1 = 7 intermediate fields
        assert_eq!(intermediates.len(), 7);
    }

    #[test]
    fn test_tower() {
        let base = CapabilityField::new("base");
        let ext = CapabilityExtension::new("extend", base, vec![
            Capability::new("a", 1),
            Capability::new("b", 2),
        ]);
        let tower = ext.tower();
        assert_eq!(tower.len(), 2);
        assert!(tower[0].is_simple());
        assert!(tower[1].is_simple());
    }

    #[test]
    fn test_is_finite() {
        let base = CapabilityField::new("base");
        let ext = CapabilityExtension::new("ext", base, vec![
            Capability::new("a", 1),
        ]);
        assert!(ext.is_finite());
    }
}
